In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
org_FSStats_data = pd.read_excel("../data/org_FSStats.xlsx")

print("Rows and columns:", org_FSStats_data.shape)
print("\nColumn names:")
print(org_FSStats_data.columns.tolist())

org_FSStats_data.head()

Rows and columns: (28287, 58)

Column names:
['__ID', '_id_site', '_Year', '_Month', 'DateForSearch', 'zzCreationTS', 'zzModificationTS', 'AdultsReg', 'ChildrenReg', 'HouseholdsReg', 'IndividualsReg', 'Meals', 'Misc', 'People', 'PoundsReg', 'SeniorsReg', 'Snacks', 'UniqueVisitsReg', 'County', 'FederalDistrict', 'StateDistrict', 'FoodBank', 'ChildrenExtra', 'ChildrenProduce', 'ChildrenHoliday', 'AdultsExtra', 'AdultsProduce', 'AdultsHoliday', 'IndividualsExtra', 'SeniorsExtra', 'SeniorsProduce', 'SeniorsHoliday', 'IndividualsProduce', 'IndividualsHoliday', 'UniqueVisitsExtra', 'UniqueVisitsProduce', 'UniqueVisitsHoliday', 'UniqueVisitsTotal', 'SeniorsTotal', 'IndividualsTotal', 'ChildrenTotal', 'AdultsTotal', 'HouseholdsExtra', 'HouseholdsProduce', 'HouseholdsHoliday', 'HouseholdsTotal', 'PoundsExtra', 'PoundsProduce', 'PoundsHoliday', 'PoundsTotal', 'AgencyType', '_id_bank', 'SuperShelf', '_YearMonth', 'PoundsPerIndiv', 'IndividualsPerHH', 'id_agency', 'PoundsPerHH']

,__ID,_id_site,_Year,_Month,DateForSearch,zzCreationTS,zzModificationTS,AdultsReg,ChildrenReg,HouseholdsReg,...,PoundsHoliday,PoundsTotal,AgencyType,_id_bank,SuperShelf,_YearMonth,PoundsPerIndiv,IndividualsPerHH,id_agency,PoundsPerHH
0,2753,1254.0,2022,1,2022-01-01,2022-01-10T21:48:14Z,2025-12-30T13:50:18Z,1519.0,1048.0,1027.0,...,NaN,41548.0,Brick and Mortar Site,6.0,NaN,202201,15.0,3.0,NaN,40.0
1,2762,14434.0,2022,1,2022-01-01,2022-01-10T15:01:29Z,2025-12-30T13:50:18Z,23.0,16.0,17.0,...,NaN,900.0,Brick and Mortar Site,1.0,NaN,202201,19.0,3.0,14434.0,53.0
2,12862,1069.0,2022,3,2022-03-01,2022-03-02T16:18:49Z,2026-09-02T20:20:24Z,281.0,27.0,220.0,...,NaN,21345.0,Food Shelf,14179.0,NaN,202203,62.0,2.0,16988.0,97.0
3,12863,1069.0,2022,1,2022-01-01,2022-03-08T09:50:31Z,2026-09-02T20:20:24Z,281.0,21.0,216.0,...,NaN,15684.0,Food Shelf,14179.0,NaN,202201,48.0,2.0,16988.0,73.0
4,12864,14680.1,2022,1,2022-01-01,2022-03-08T09:50:31Z,2025-12-30T13:50:24Z,142.0,93.0,91.0,...,NaN,5761.0,Tribal Program,14179.0,NaN,202201,22.0,3.0,NaN,63.0

In [3]:
q6_clean = org_FSStats_data.copy()

# Standardize county names
county_mapping = {
    "Hennepin-Minneapolis": "Hennepin",
    "Hennepin-Suburbs": "Hennepin",
    "Ramsey-Saint Paul": "Ramsey",
    "Ramsey-Suburbs": "Ramsey",
    "Saint Louis": "St. Louis"
}

q6_clean["County"] = (
    q6_clean["County"]
    .str.strip()
    .replace(county_mapping)
)

In [4]:
org_data = pd.read_excel("../data/Organization.xlsx")

print("Shape:", org_data.shape)
print("\nColumns:")
print(org_data.columns.tolist())

org_data.head()

Shape: (1202, 68)

Columns:
['__ID', 'CreateTime', 'zzCreationTS', 'zzModificationTS', '_id_type', 'City', 'State', 'Zip', 'MailCity', 'MailState', 'MailZip', 'Eligibility', 'Conditions', 'MarketSeasons', 'zcountDaysOperations', 'Region', 'SuperRegion', 'County', 'StateDistrict', 'FederalDistrict', 'DistrictSection', 'AgencyType', '_id_subtype', 'AgencySubType', 'isFoodBank', 'isAgency', 'isDistributionSite', 'HoldsInventoryForOthers', 'isWebscmShipTo', 'WebscmShipToName', 'StateClass', 'MFS', 'MCS', 'cCountSites', 'isActive', 'ActiveInactive', 'InactiveDate', 'TaxEINVerifiedYN', 'TaxEINVerifiedDate', 'TaxEINVerifiedMethod', 'isTEFAPEligible', 'isTEFAPEligible_Alert', 'TefapStatus', 'TefapActiveDate', 'TefapInActiveDate', 'TEFAPElligibilityMeans', 'SuperShelfStatus', 'SuperShelfCertDate', '_id_Bank', '_id_Agency', '_id_IfFoodBank', 'isFindHelpMap', 'FindHelpMapCategory', '_id_findhelpMapCat', 'z12MoAverage_children', 'z12MoAverage_Adults', 'z12MoAverage_Senior', 'z12MoAverage_Indiv', 'z12MoAverage_House', 'z12MoAverage_Pounds', 'z12MoAverage_LlbsPerPerson', 'z12MoAverage_PeoplePerHouse', 'z12MoAverage_TEFAPCases', 'z12MoAverage_LlbsPerHH', 'z12MoAverage_Meals', 'zNameIfActiveBank', 'block_geoid', 'is_zip_centroid']

,__ID,CreateTime,zzCreationTS,zzModificationTS,_id_type,City,State,Zip,MailCity,MailState,...,z12MoAverage_House,z12MoAverage_Pounds,z12MoAverage_LlbsPerPerson,z12MoAverage_PeoplePerHouse,z12MoAverage_TEFAPCases,z12MoAverage_LlbsPerHH,z12MoAverage_Meals,zNameIfActiveBank,block_geoid,is_zip_centroid
0,1.0,System.Byte[],NaN,2026-05-15T19:15:18Z,11.0,Rochester,MN,55904.0,Rochester,MN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Channel One Regional Food Bank*,2.710900e+14,0.0
1,3.0,System.Byte[],NaN,2026-08-06T10:27:10Z,1.0,Brooklyn Park,MN,55428.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Second Harvest Heartland,2.705303e+14,0.0
2,5.0,System.Byte[],NaN,2026-09-01T02:10:43Z,1.0,East Grand Forks,MN,56721.0,East Grand Forks,MN,...,NaN,NaN,NaN,NaN,530.0,NaN,NaN,North Country Food Bank Inc.,2.711902e+14,0.0
3,6.0,System.Byte[],NaN,2026-09-03T10:32:32Z,1.0,Duluth,MN,55808.0,Duluth,MN,...,NaN,NaN,NaN,NaN,108.0,NaN,NaN,Second Harvest Northland,2.713700e+14,0.0
4,7.0,System.Byte[],NaN,2026-01-07T13:35:05Z,1.0,Fargo,ND,58102.0,Fargo,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.801700e+14,0.0

In [5]:
# Create indicator columns for broad site categories
site_rows = q6_clean[
    q6_clean["_Month"].between(1, 12)
].copy()

site_rows["is_core_shelf"] = site_rows["AgencyType"].isin([
    "Food Shelf",
    "Brick and Mortar Site",
    "Brick and Mortar Sites"
])

site_rows["is_mobile_outreach"] = site_rows["AgencyType"].isin([
    "Mobile",
    "Outreach Program"
])

site_rows["is_meal_program"] = site_rows["AgencyType"].isin([
    "Meal Program",
    "Meal Programs",
    "On-Site Meal Programs"
])

site_rows["is_college"] = (
    site_rows["AgencyType"] == "College Campus Program"
)

site_rows["is_tribal"] = (
    site_rows["AgencyType"] == "Tribal Program"
)

site_class = (
    site_rows
    .groupby("_id_site")[
        [
            "is_core_shelf",
            "is_mobile_outreach",
            "is_meal_program",
            "is_college",
            "is_tribal"
        ]
    ]
    .max()
    .reset_index()
)

display(site_class.head())

conditions = [
    site_class["is_core_shelf"] & site_class["is_mobile_outreach"],
    site_class["is_core_shelf"],
    site_class["is_mobile_outreach"],
    site_class["is_meal_program"],
    site_class["is_college"],
    site_class["is_tribal"]
]

choices = [
    "Food Shelf / Outreach",
    "Food Shelf",
    "Mobile / Outreach",
    "Meal Program",
    "College Program",
    "Tribal Program"
]

site_class["stable_type"] = np.select(
    conditions,
    choices,
    default="Other"
)

print(site_class["stable_type"].value_counts())

,_id_site,is_core_shelf,is_mobile_outreach,is_meal_program,is_college,is_tribal
0,1066.0,True,False,False,False,False
1,1067.0,True,False,False,False,False
2,1069.0,True,False,False,False,False
3,1070.0,True,False,False,False,False
4,1071.0,True,False,False,False,False

stable_type
Food Shelf               447
Meal Program              65
Other                     55
Mobile / Outreach         52
Food Shelf / Outreach     41
Tribal Program             4
College Program            1
Name: count, dtype: int64

In [6]:
# Invalid month records
metrics = [
    "HouseholdsReg",
    "IndividualsReg",
    "PoundsReg"
]
invalid_month_rows = q6_clean[
    ~q6_clean["_Month"].between(1, 12)
].copy()

month0 = invalid_month_rows[
    invalid_month_rows["_Month"] == 0
].copy()

month15 = invalid_month_rows[
    invalid_month_rows["_Month"] == 15
].copy()

print("Month 0 rows:", len(month0))
print("Month 15 rows:", len(month15))

dec_2023 = q6_clean[
    (q6_clean["_Year"] == 2023) &
    (q6_clean["_Month"] == 12)
][
    [
        "_id_site",
        "HouseholdsReg",
        "IndividualsReg",
        "PoundsReg"
    ]
].copy()

month0_check = month0.merge(
    dec_2023,
    on="_id_site",
    how="left",
    suffixes=("_month0", "_dec2023")
)

for col in metrics:
    month0_check[col + "_same"] = (
        month0_check[col + "_month0"].fillna(-999999)
        ==
        month0_check[col + "_dec2023"].fillna(-999999)
    )

same_columns = [
    "HouseholdsReg_same",
    "IndividualsReg_same",
    "PoundsReg_same"
]

month0_check["all_three_same"] = (
    month0_check[same_columns].all(axis=1)
)

print("Month-0 rows matching December 2023 exactly:")
print(month0_check["all_three_same"].value_counts())

display(
    month0_check[
        [
            "_id_site",
            "HouseholdsReg_month0",
            "HouseholdsReg_dec2023",
            "IndividualsReg_month0",
            "IndividualsReg_dec2023",
            "PoundsReg_month0",
            "PoundsReg_dec2023",
            "all_three_same"
        ]
    ]
)

march_2024 = q6_clean[
    (q6_clean["_Year"] == 2024) &
    (q6_clean["_Month"] == 3)
][
    [
        "_id_site",
        "HouseholdsReg",
        "IndividualsReg",
        "PoundsReg"
    ]
].copy()

month15_check = month15.merge(
    march_2024,
    on="_id_site",
    how="left",
    suffixes=("_month15", "_mar2024")
)

display(month15_check)

Month 0 rows: 25
Month 15 rows: 1
Month-0 rows matching December 2023 exactly:
all_three_same
True    25
Name: count, dtype: int64

,_id_site,HouseholdsReg_month0,HouseholdsReg_dec2023,IndividualsReg_month0,IndividualsReg_dec2023,PoundsReg_month0,PoundsReg_dec2023,all_three_same
0,14810.0,54.0,54.0,129.0,129.0,1785.0,1785.0,True
1,1072.0,183.0,183.0,421.0,421.0,8778.0,8778.0,True
2,14717.0,332.0,332.0,755.0,755.0,11625.0,11625.0,True
3,1103.0,274.0,274.0,691.0,691.0,12128.0,12128.0,True
4,1088.0,691.0,691.0,1106.0,1106.0,40515.0,40515.0,True
5,1110.0,146.0,146.0,463.0,463.0,13535.0,13535.0,True
6,1108.0,97.0,97.0,202.0,202.0,5820.0,5820.0,True
7,1250.0,118.0,118.0,188.0,188.0,6948.0,6948.0,True
8,1410.0,653.0,653.0,1772.0,1772.0,37695.0,37695.0,True
9,1128.0,36.0,36.0,59.0,59.0,1295.0,1295.0,True
10,1413.0,219.0,219.0,496.0,496.0,17332.0,17332.0,True
11,1145.0,46.0,46.0,118.0,118.0,3178.0,3178.0,True
12,1149.0,96.0,96.0,182.0,182.0,6330.0,6330.0,True
13,14715.0,60.0,60.0,136.0,136.0,4153.0,4153.0,True
14,14742.0,71.0,71.0,183.0,183.0,4505.0,4505.0,True
15,1254.0,167.0,167.0,474.0,474.0,11895.0,11895.0,True
16,1135.0,185.0,185.0,449.0,449.0,11144.0,11144.0,True
17,1226.0,120.0,120.0,287.0,287.0,7284.0,7284.0,True
18,1228.0,809.0,809.0,2444.0,2444.0,83595.0,83595.0,True
19,1218.0,1461.0,1461.0,3577.0,3577.0,103637.0,103637.0,True
20,1266.0,33.0,33.0,81.0,81.0,1684.0,1684.0,True
21,1284.0,80.0,80.0,262.0,262.0,3723.0,3723.0,True
22,13624.0,79.0,79.0,176.0,176.0,8022.0,8022.0,True
23,1286.0,318.0,318.0,722.0,722.0,22447.0,22447.0,True
24,1259.0,20.0,20.0,60.0,60.0,1000.0,1000.0,True

,__ID,_id_site,_Year,_Month,DateForSearch,zzCreationTS,zzModificationTS,AdultsReg,ChildrenReg,HouseholdsReg_month15,...,_id_bank,SuperShelf,_YearMonth,PoundsPerIndiv,IndividualsPerHH,id_agency,PoundsPerHH,HouseholdsReg_mar2024,IndividualsReg_mar2024,PoundsReg_mar2024
0,23361,1148.0,2023,15,2024-03-01,2023-09-18T11:26:15Z,2025-12-30T13:50:30Z,37.0,15.0,33.0,...,5.0,NaN,202315,30.0,2.0,16246.0,62.0,43.0,97.0,2902.4

In [7]:
# Remove the 26 invalid-month duplicate records
valid_month_mask = q6_clean["_Month"].between(1, 12)

q6_valid_months = q6_clean[
    valid_month_mask
].copy()

print("Original rows:", len(q6_clean))
print("Rows removed:", len(q6_clean) - len(q6_valid_months))
print("Rows remaining:", len(q6_valid_months))

print(
    "Invalid months remaining:",
    (~q6_valid_months["_Month"].between(1, 12)).sum()
)

Original rows: 28287
Rows removed: 26
Rows remaining: 28261
Invalid months remaining: 0

In [8]:
metrics = [
    "HouseholdsReg",
    "IndividualsReg",
    "PoundsReg"
]

# Rows with a known county and all 3 Q6 measures observed
known_complete = q6_valid_months[
    q6_valid_months["County"].notna() &
    q6_valid_months[metrics].notna().all(axis=1)
].copy()

# Rows with missing county and all 3 measures observed
missing_complete = q6_valid_months[
    q6_valid_months["County"].isna() &
    q6_valid_months[metrics].notna().all(axis=1)
].copy()

# Preserve original row index so we know which rows to remove
missing_complete = (
    missing_complete
    .reset_index()
    .rename(columns={"index": "source_index"})
)

match_columns = [
    "_Year",
    "_Month",
    "HouseholdsReg",
    "IndividualsReg",
    "PoundsReg"
]

exact_matches = missing_complete.merge(
    known_complete[
        ["_id_site", "County"] + match_columns
    ],
    on=match_columns,
    how="left",
    suffixes=("_missing", "_known")
)

confirmed_duplicates = exact_matches[
    exact_matches["_id_site_known"].notna()
].copy()

duplicate_indices = (
    confirmed_duplicates["source_index"]
    .drop_duplicates()
    .tolist()
)

print("Confirmed blank-county duplicate rows:",
      len(duplicate_indices))

q6_no_duplicates = q6_valid_months[
    ~q6_valid_months.index.isin(duplicate_indices)
].copy()

print("Rows before duplicate removal:",
      len(q6_valid_months))

print("Duplicate rows removed:",
      len(q6_valid_months) - len(q6_no_duplicates))

print("Rows remaining:",
      len(q6_no_duplicates))

remaining_missing = q6_no_duplicates[
    q6_no_duplicates["County"].isna()
].copy()

print("Remaining rows with missing county:",
      len(remaining_missing))

print("Unique unresolved sites:",
      remaining_missing["_id_site"].nunique())

print("\nBy year:")
print(
    remaining_missing["_Year"]
    .value_counts()
    .sort_index()
)

Confirmed blank-county duplicate rows: 87
Rows before duplicate removal: 28261
Duplicate rows removed: 87
Rows remaining: 28174
Remaining rows with missing county: 45
Unique unresolved sites: 16

By year:
_Year
2022     6
2023    18
2024     9
2025     3
2026     9
Name: count, dtype: int64

In [9]:
unresolved = q6_no_duplicates[
    q6_no_duplicates["County"].isna()
].copy()

print("Agency types:")
print(unresolved["AgencyType"].value_counts(dropna=False))

print("\nFood banks:")
print(unresolved["FoodBank"].value_counts(dropna=False))

for col in ["HouseholdsReg", "IndividualsReg", "PoundsReg"]:

    unresolved_total = unresolved[col].sum()
    overall_total = q6_no_duplicates[col].sum()

    percent = 100 * unresolved_total / overall_total

    print(
        col,
        ":",
        round(unresolved_total, 2),
        "(",
        round(percent, 3),
        "%)"
    )

unresolved_summary = (
    unresolved
    .groupby("_id_site")
    .agg(
        rows=("_Month", "count"),
        first_year=("_Year", "min"),
        last_year=("_Year", "max"),
        households=("HouseholdsReg", "sum"),
        individuals=("IndividualsReg", "sum"),
        pounds=("PoundsReg", "sum")
    )
    .reset_index()
)

display(unresolved_summary)

Agency types:
AgencyType
NaN                 22
Meal Program        19
Outreach Program     3
Food Shelf           1
Name: count, dtype: int64

Food banks:
FoodBank
Second Harvest Northland    19
Second Harvest Heartland    17
NaN                          8
North Central Food Bank      1
Name: count, dtype: int64
HouseholdsReg : 13662.0 ( 0.11 %)
IndividualsReg : 40124.0 ( 0.109 %)
PoundsReg : 512799.0 ( 0.078 %)

    _id_site  rows  first_year  last_year  households  individuals    pounds
0    15218.0    19        2022       2026         0.0          0.0       0.0
1    15362.0     1        2023       2023      1433.0       4048.0   72020.0
2    15363.0     1        2023       2023      1433.0       4048.0    7202.0
3    15364.0     2        2023       2024       420.0       1502.0   13974.0
4    15366.0     1        2023       2023      3752.0       8328.0  160744.0
5    15367.0     1        2023       2023         0.0          0.0       0.0
6    15383.0     1        2024       2024        86.0        247.0    3326.0
7    15389.0     2        2023       2024      1131.0       3103.0       0.0
8    15390.0     1        2024       2024       436.0        371.0   27251.0
9    15398.0     1        2024       2024         0.0          0.0       0.0
10   15399.0     1        2024       2024       966.0       2683.0   53145.0
11   15425.0     1        2024       2024        56.0        101.0       0.0
12   15432.0     1        2024       2024         0.0          0.0       0.0
13   15433.0     1        2024       2024       311.0        990.0       0.0
14   16486.0     4        2025       2026       456.0       1414.0   16837.0
15   16597.0     7        2026       2026      3182.0      13289.0  158300.0

In [10]:
# Start from the data after:
# 1. removing invalid-month duplicates
# 2. removing confirmed blank-county duplicate feeds

site_month_clean = q6_no_duplicates.copy()

# Add the stable site classification we created earlier
site_month_clean = site_month_clean.merge(
    site_class[
        ["_id_site", "stable_type"]
    ],
    on="_id_site",
    how="left"
)

# Add official Organization flags
org_flags = org_data[
    [
        "__ID",
        "isDistributionSite",
        "isAgency",
        "isActive",
        "block_geoid"
    ]
].copy()

site_month_clean = site_month_clean.merge(
    org_flags,
    left_on="_id_site",
    right_on="__ID",
    how="left",
    suffixes=("", "_org")
)

# Flag whether geographic location is usable
site_month_clean["location_resolved"] = (
    site_month_clean["County"].notna()
)
print("Final cleaned rows:", len(site_month_clean))

print("\nYears:")
print(
    site_month_clean["_Year"]
    .value_counts()
    .sort_index()
)

print("\nLocation resolved:")
print(
    site_month_clean["location_resolved"]
    .value_counts()
)

print("\nStable site types:")
print(
    site_month_clean["stable_type"]
    .value_counts(dropna=False)
)

Final cleaned rows: 28174

Years:
_Year
2022    5959
2023    6511
2024    6173
2025    6023
2026    3508
Name: count, dtype: int64

Location resolved:
location_resolved
True     28129
False       45
Name: count, dtype: int64

Stable site types:
stable_type
Food Shelf               21574
Meal Program              2700
Food Shelf / Outreach     1966
Mobile / Outreach         1648
Tribal Program             219
Other                       57
College Program             10
Name: count, dtype: int64

In [11]:
sites_to_check = [1189, 1365]

kanabec_check = site_month_clean[
    site_month_clean["_id_site"].isin(sites_to_check)
].copy()

counts = (
    kanabec_check
    .groupby(["_id_site", "_Year", "_Month"])
    .size()
    .reset_index(name="n_rows")
)

repeated_months = counts[
    counts["n_rows"] > 1
][
    ["_id_site", "_Year", "_Month"]
]

kanabec_duplicates = kanabec_check.merge(
    repeated_months,
    on=["_id_site", "_Year", "_Month"],
    how="inner"
)

display(
    kanabec_duplicates[
        [
            "_id_site",
            "_Year",
            "_Month",
            "__ID",
            "HouseholdsReg",
            "IndividualsReg",
            "PoundsReg"
        ]
    ].sort_values(
        ["_id_site", "_Year", "_Month", "__ID"]
    )
)

duplicate_value_check = (
    kanabec_duplicates
    .groupby(["_id_site", "_Year", "_Month"])
    .agg(
        household_values=("HouseholdsReg", "nunique"),
        individual_values=("IndividualsReg", "nunique"),
        pound_values=("PoundsReg", "nunique"),
        row_count=("__ID", "count")
    )
    .reset_index()
)

display(duplicate_value_check)

site_month_clean.to_csv(
    "../data/processed/site_month_clean.csv",
    index=False
)

    _id_site  _Year  _Month   __ID  HouseholdsReg  IndividualsReg  PoundsReg
0     1189.0   2024       2  31081          261.0           710.0    14225.0
1     1189.0   2024       2  31082          261.0           710.0    14225.0
2     1365.0   2024       2  31086           92.0           239.0     4593.0
3     1365.0   2024       2  31087           92.0           239.0     4593.0
4     1365.0   2024       3  31124            0.0             0.0        0.0
5     1365.0   2024       3  31130           80.0           210.0     7737.0
6     1365.0   2024       4  31168           36.0            82.0     1772.0
7     1365.0   2024       4  31174           89.0           207.0     1772.0
8     1365.0   2024       5  31212           26.0            55.0     2621.0
9     1365.0   2024       5  31219           71.0           110.0    13206.0
10    1365.0   2024       6  31257           32.0            71.0     1703.0
11    1365.0   2024       6  31263           92.0           207.0     3348.0
12    1365.0   2024       7  31301           31.0            63.0     1995.0
13    1365.0   2024       7  31307          101.0           249.0     8499.0
14    1365.0   2024       8  31345           46.0            89.0     3551.0
15    1365.0   2024       8  31351           92.0           252.0     3681.0
16    1365.0   2024       9  31389           57.0           116.0     2247.0
17    1365.0   2024       9  31395           92.0           252.0     3681.0
18    1365.0   2024      10  31433           97.0           205.0     4837.0
19    1365.0   2024      10  31439           70.0           156.0     9423.0
20    1365.0   2024      11  31477           62.0           136.0     3472.0
21    1365.0   2024      11  31483          101.0           238.0     3906.0
22    1365.0   2024      12  31521           47.0            96.0     2006.0
23    1365.0   2024      12  31527           71.0           145.0     7567.0
24    1365.0   2025       1  31998           89.0           204.0     2945.0
25    1365.0   2025       1  32005           89.0           204.0     2945.0
26    1365.0   2025       2  32863           85.0           186.0     3522.0
27    1365.0   2025       2  32869           85.0           186.0     3522.0

,_id_site,_Year,_Month,household_values,individual_values,pound_values,row_count
0,1189.0,2024,2,1,1,1,2
1,1365.0,2024,2,1,1,1,2
2,1365.0,2024,3,2,2,2,2
3,1365.0,2024,4,2,2,1,2
4,1365.0,2024,5,2,2,2,2
5,1365.0,2024,6,2,2,2,2
6,1365.0,2024,7,2,2,2,2
7,1365.0,2024,8,2,2,2,2
8,1365.0,2024,9,2,2,2,2
9,1365.0,2024,10,2,2,2,2
10,1365.0,2024,11,2,2,2,2
11,1365.0,2024,12,2,2,2,2
12,1365.0,2025,1,1,1,1,2
13,1365.0,2025,2,1,1,1,2

In [12]:
# Site 1189: remove the duplicate February 2024 resubmission
mask_1189_dup = (
    (site_month_clean["_id_site"] == 1189) &
    (site_month_clean["_Year"] == 2024) &
    (site_month_clean["_Month"] == 2)
)

rows_1189 = site_month_clean[mask_1189_dup].copy()

# Keep the first one, remove the second
drop_index_1189 = rows_1189.index[1]

site_month_clean = site_month_clean.drop(
    index=drop_index_1189
)

print(
    site_month_clean[
        (site_month_clean["_id_site"] == 1189) &
        (site_month_clean["_Year"] == 2024) &
        (site_month_clean["_Month"] == 2)
    ][
        [
            "_id_site",
            "_Year",
            "_Month",
            "HouseholdsReg",
            "IndividualsReg",
            "PoundsReg"
        ]
    ]
)

site_month_clean["County"] = site_month_clean["County"].replace({
    "Lac Qui Parle": "Lac qui Parle"
})

site_month_clean.to_csv(
    "../data/processed/site_month_clean.csv",
    index=False
)

       _id_site  _Year  _Month  HouseholdsReg  IndividualsReg  PoundsReg
17842    1189.0   2024       2          261.0           710.0    14225.0

The original activity file contained 28,287 rows. Twenty-six invalid-month records and 87 blank-county duplicate-feed records were removed. One exact duplicate site-month record for site 1189 was removed, followed by 19 rows belonging to six persistent mirror-site IDs. Forty-five rows across 16 sites still lack reliable county information; these are retained in the master file but excluded from county-level analyses. Seven implausible household-count entries were corrected using each site's median household count calculated from non-flagged rows. The final cleaned dataset contains 28,154 rows

In [13]:
metrics = [
    "HouseholdsReg",
    "IndividualsReg",
    "PoundsReg"
]

match_columns = [
    "_Year",
    "_Month",
    "HouseholdsReg",
    "IndividualsReg",
    "PoundsReg"
]

# Use valid-month data before blank-county duplicates
# were removed, so the mirror evidence is still present.
mirror_base = q6_valid_months[
    q6_valid_months[metrics].notna().all(axis=1) &
    (q6_valid_months["HouseholdsReg"] >= 20) &
    (q6_valid_months["PoundsReg"] > 0)
][
    ["_id_site"] + match_columns
].copy()

mirror_base = mirror_base.drop_duplicates()

In [14]:
site_pairs = mirror_base.merge(
    mirror_base,
    on=match_columns,
    how="inner",
    suffixes=("_a", "_b")
)

# Remove self-matches and reversed duplicates
site_pairs = site_pairs[
    site_pairs["_id_site_a"] < site_pairs["_id_site_b"]
].copy()

site_pairs["year_month"] = (
    site_pairs["_Year"].astype(str)
    + "-"
    + site_pairs["_Month"].astype(str).str.zfill(2)
)

pair_summary = (
    site_pairs
    .groupby(
        ["_id_site_a", "_id_site_b"],
        as_index=False
    )
    .agg(
        matching_months=("year_month", "nunique")
    )
)

# Require at least 3 matching months
mirror_pairs = pair_summary[
    pair_summary["matching_months"] >= 3
].copy()

In [15]:
mirror_ids = [
    15361,
    15362,
    15363,
    15364,
    15365,
    15366
]

mirror_evidence = mirror_pairs[
    mirror_pairs["_id_site_a"].isin(mirror_ids) |
    mirror_pairs["_id_site_b"].isin(mirror_ids)
].sort_values(
    "matching_months",
    ascending=False
)

display(mirror_evidence)

    _id_site_a  _id_site_b  matching_months
38     14072.0     15365.0               13
55     14801.0     15361.0               13
29      1279.0     15366.0               12
21      1207.0     15362.0               11
53     14659.0     15363.0               11
54     14719.0     15364.0               11

In [16]:
mirror_rows = site_month_clean[
    site_month_clean["_id_site"].isin(mirror_ids)
].copy()

print("Mirror rows removed:", len(mirror_rows))

site_month_clean = site_month_clean[
    ~site_month_clean["_id_site"].isin(mirror_ids)
].copy()

print("Rows after mirror removal:", len(site_month_clean))

Mirror rows removed: 19
Rows after mirror removal: 28154

In [17]:
# Detect extreme HouseholdReg values using three independent checks.

site_household_median = (
    site_month_clean
    .groupby("_id_site")[
        "HouseholdsReg"
    ]
    .transform("median")
)

rule_households_vs_individuals = (
    site_month_clean["HouseholdsReg"]
    >
    1.5
    * site_month_clean["IndividualsReg"]
)

rule_households_equal_pounds = (
    site_month_clean["HouseholdsReg"].notna()
    &
    site_month_clean["PoundsReg"].notna()
    &
    (
        site_month_clean["HouseholdsReg"]
        ==
        site_month_clean["PoundsReg"]
    )
)

rule_extreme_vs_site = (
    (
        site_month_clean["HouseholdsReg"]
        >
        10 * site_household_median
    )
    &
    (
        site_month_clean["HouseholdsReg"]
        > 500
    )
)

outlier_rule_count = (
    rule_households_vs_individuals.astype(int)
    +
    rule_households_equal_pounds.astype(int)
    +
    rule_extreme_vs_site.astype(int)
)

household_outlier = (
    outlier_rule_count >= 2
)

outlier_audit = site_month_clean.loc[
    household_outlier,
    [
        "_id_site",
        "_Year",
        "_Month",
        "County",
        "HouseholdsReg",
        "IndividualsReg",
        "PoundsReg"
    ]
].copy()

outlier_audit[
    "rules_triggered"
] = outlier_rule_count[
    household_outlier
].to_numpy()

print(
    "Household outliers detected:",
    len(outlier_audit)
)

display(
    outlier_audit.sort_values(
        [
            "_Year",
            "_Month",
            "_id_site"
        ]
    )
)

Household outliers detected: 7

,_id_site,_Year,_Month,County,HouseholdsReg,IndividualsReg,PoundsReg,rules_triggered
9095,1245.0,2023,6,Polk,2247.0,706.0,36550.0,2
9561,1197.0,2023,7,Waseca,273385.0,646.0,12053.0,2
14078,15306.0,2024,4,Dakota,3257.0,371.0,3257.0,3
17216,1083.0,2024,11,Hennepin,4203.0,1882.0,27039.0,2
19885,1304.0,2025,3,Ramsey,83909.0,13735.0,83909.0,3
21627,1277.0,2025,7,Marshall,1590.0,49.0,NaN,2
23581,1417.0,2025,11,Hubbard,6670.0,239.0,NaN,2

In [18]:
# Build site medians using only non-outlier rows
household_reference = site_month_clean[
    ~household_outlier
][
    [
        "_id_site",
        "HouseholdsReg"
    ]
].copy()

site_household_medians = (
    household_reference
    .groupby("_id_site")[
        "HouseholdsReg"
    ]
    .median()
)

# Create an audit table before changing anything
household_outlier_audit = site_month_clean.loc[
    household_outlier,
    [
        "_id_site",
        "_Year",
        "_Month",
        "County",
        "HouseholdsReg",
        "IndividualsReg",
        "PoundsReg"
    ]
].copy()

household_outlier_audit = (
    household_outlier_audit
    .rename(
        columns={
            "HouseholdsReg":
                "original_households"
        }
    )
)

household_outlier_audit[
    "replacement_households"
] = (
    household_outlier_audit[
        "_id_site"
    ]
    .map(
        site_household_medians
    )
)

print(
    "Outliers to replace:",
    len(
        household_outlier_audit
    )
)

print(
    "Missing replacement medians:",
    household_outlier_audit[
        "replacement_households"
    ]
    .isna()
    .sum()
)

display(
    household_outlier_audit[
        [
            "_id_site",
            "_Year",
            "_Month",
            "County",
            "original_households",
            "replacement_households",
            "IndividualsReg",
            "PoundsReg"
        ]
    ]
)

Outliers to replace: 7
Missing replacement medians: 0

,_id_site,_Year,_Month,County,original_households,replacement_households,IndividualsReg,PoundsReg
9095,1245.0,2023,6,Polk,2247.0,219.0,706.0,36550.0
9561,1197.0,2023,7,Waseca,273385.0,403.0,646.0,12053.0
14078,15306.0,2024,4,Dakota,3257.0,62.5,371.0,3257.0
17216,1083.0,2024,11,Hennepin,4203.0,399.5,1882.0,27039.0
19885,1304.0,2025,3,Ramsey,83909.0,2702.0,13735.0,83909.0
21627,1277.0,2025,7,Marshall,1590.0,21.5,49.0,NaN
23581,1417.0,2025,11,Hubbard,6670.0,77.0,239.0,NaN

In [19]:
replacement_values = (
    site_month_clean.loc[
        household_outlier,
        "_id_site"
    ]
    .map(
        site_household_medians
    )
)

site_month_clean.loc[
    household_outlier,
    "HouseholdsReg"
] = (
    replacement_values.to_numpy()
)

display(
    site_month_clean.loc[
        household_outlier,
        [
            "_id_site",
            "_Year",
            "_Month",
            "County",
            "HouseholdsReg",
            "IndividualsReg",
            "PoundsReg"
        ]
    ]
)

,_id_site,_Year,_Month,County,HouseholdsReg,IndividualsReg,PoundsReg
9095,1245.0,2023,6,Polk,219.0,706.0,36550.0
9561,1197.0,2023,7,Waseca,403.0,646.0,12053.0
14078,15306.0,2024,4,Dakota,62.5,371.0,3257.0
17216,1083.0,2024,11,Hennepin,399.5,1882.0,27039.0
19885,1304.0,2025,3,Ramsey,2702.0,13735.0,83909.0
21627,1277.0,2025,7,Marshall,21.5,49.0,NaN
23581,1417.0,2025,11,Hubbard,77.0,239.0,NaN

In [20]:
site_household_median_check = (
    site_month_clean
    .groupby("_id_site")[
        "HouseholdsReg"
    ]
    .transform("median")
)

check_rule_1 = (
    site_month_clean[
        "HouseholdsReg"
    ]
    >
    1.5
    * site_month_clean[
        "IndividualsReg"
    ]
)

check_rule_2 = (
    site_month_clean[
        "HouseholdsReg"
    ].notna()
    &
    site_month_clean[
        "PoundsReg"
    ].notna()
    &
    (
        site_month_clean[
            "HouseholdsReg"
        ]
        ==
        site_month_clean[
            "PoundsReg"
        ]
    )
)

check_rule_3 = (
    (
        site_month_clean[
            "HouseholdsReg"
        ]
        >
        10
        * site_household_median_check
    )
    &
    (
        site_month_clean[
            "HouseholdsReg"
        ]
        > 500
    )
)

remaining_bad_rows = (
    check_rule_1.astype(int)
    +
    check_rule_2.astype(int)
    +
    check_rule_3.astype(int)
) >= 2

print(
    "Remaining household outliers:",
    remaining_bad_rows.sum()
)

Remaining household outliers: 0

In [21]:
household_outlier_audit.to_csv(
    "../data/processed/"
    "household_outlier_corrections.csv",
    index=False
)

site_month_clean.to_csv(
    "../data/processed/"
    "site_month_clean.csv",
    index=False
)

print(
    "Clean rows saved:",
    len(site_month_clean)
)

print(
    "Correction audit rows saved:",
    len(
        household_outlier_audit
    )
)

Clean rows saved: 28154
Correction audit rows saved: 7